GET http://localhost:3000/products.json
Authorization:  Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODk3MjczNDd9.uKDJpqe5pay7zkxuSd2l9UAwLioRIp8uDg_1uB5fSjM
###
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name":"stan smith",
  "price":80,
  "image_url":"www.addidas.com",
  "description":"white tennis sneakers"
}
###
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "name":"blazer" ,
  "image_url":"https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/fb7eda3c-5ac8-4d05-a18f-1c2c5e82e36e/blazer-mid-77-vintage-mens-shoes-nw30B2.png"
}
###
delete http://localhost:3000/products/2.json
Content-Type:application/json
###

POST http://localhost:3000/users.json
Content-Type: application/json

# {
#   "name": "kim",
#   "email": "kim@test.com",
#   "password":"password",
#   "password_confirmation":"password"
# }

{
  "name": "Josh",
  "email": "Josh@test.com",
  "password":"password",
  "password_confirmation":"password"
}
###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email":"Josh@test.com",
  "password":"password"
}
###
POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "id": 2,
  "user_id":1,
  "product_id": 3,
  "quantity": 1,
  "subtotal": 700,
  "tax": 25,
  "total":725
}